[tool.briefcase]
project_name = "YouTube Video Downloader"
version = "0.1.0"
description = "A simple YouTube video downloader application."
author = "Your Name"
author_email = "your.email@example.com"
url = "https://github.com/mvp-2003/YT-video-downloader"
license = { file = "LICENSE" }
bundle = "com.example"

[tool.briefcase.app.youtube_video_downloader]
sources = ["youtube_video_downloader"]
requires = ["customtkinter", "pytube", "requests", "validators"]